export const TIME_SECONDS = {
  DAY: 86400,
  HOUR: 3600,
  MINUTE: 60,
  MONTH: 2592000,
  SECOND: 1,
  WEEK: 604800,
  YEAR: 31536000,
} as const;

export const MILLISECONDS_PER_SECOND = 1000;

export const TIME_MILLISECONDS = {
  DAY: TIME_SECONDS.DAY * MILLISECONDS_PER_SECOND,
  HOUR: TIME_SECONDS.HOUR * MILLISECONDS_PER_SECOND,
  MINUTE: TIME_SECONDS.MINUTE * MILLISECONDS_PER_SECOND,
  MONTH: TIME_SECONDS.MONTH * MILLISECONDS_PER_SECOND,
  SECOND: TIME_SECONDS.SECOND * MILLISECONDS_PER_SECOND,
  WEEK: TIME_SECONDS.WEEK * MILLISECONDS_PER_SECOND,
  YEAR: TIME_SECONDS.YEAR * MILLISECONDS_PER_SECOND,
} as const;
