export const MESSAGE = {
  REGISTRATION_SUCCESS: 'Registration was successful',
  REGISTRATION_ERROR: 'Registration failed',
  LOGIN_SUCCESS: 'Login was successful',
  LOGIN_ERROR: 'Login failed',
  LOGOUT_SUCCESS: 'Logout was successful',
  LOGOUT_ERROR: 'Logout failed',
  UNKNOWN_ERROR: 'An unknown error occurred',
  CREATE_PROFILE_SUCCESS: 'Profile was created',
  DELETE_PROFILE_SUCCESS: 'Profile was deleted',
  UPDATE_PROFILE_SUCCESS: 'Profile was updated',
  CREATE_AUTHOR_SUCCESS: 'Author was created',
  DELETE_AUTHOR_SUCCESS: 'Author was deleted',
  UPDATE_AUTHOR_SUCCESS: 'Author was updated',
} as const;
