export const MESSAGE = {
  ADD_ROLE_SUCCESS: 'Role was added',
  CREATE_AUTHOR_SUCCESS: 'Author was created',
  CREATE_POST_SUCCESS: 'Post was created',
  CREATE_PROFILE_SUCCESS: 'Profile was created',
  DELETE_AUTHOR_SUCCESS: 'Author was deleted',
  DELETE_POST_SUCCESS: 'Post was deleted',
  DELETE_PROFILE_SUCCESS: 'Profile was deleted',
  DELETE_USER_SUCCESS: 'User was deleted',
  LOGIN_ERROR: 'Login failed',
  LOGIN_SUCCESS: 'Login was successful',
  LOGOUT_ERROR: 'Logout failed',
  LOGOUT_SUCCESS: 'Logout was successful',
  REGISTRATION_ERROR: 'Registration failed',
  REGISTRATION_SUCCESS: 'Registration was successful',
  REMOVE_ROLE_SUCCESS: 'Role was removed',
  UNKNOWN_ERROR: 'An unknown error occurred',
  UPDATE_AUTHOR_SUCCESS: 'Author was updated',
  UPDATE_POST_SUCCESS: 'Post was updated',
  UPDATE_PROFILE_SUCCESS: 'Profile was updated',
} as const;
