export const ENDPOINTS = {
  AUTHORS: 'authors',
  GOOGLE: 'auth/google',
  GOOGLE_CALLBACK: 'auth/google/callback',
  HIERARCHY: 'hierarchy',
  IMAGES: 'images',
  LOGIN: 'auth/login',
  LOGOUT: 'auth/logout',
  ME: 'me',
  POSTS: 'posts',
  PROFILES: 'profiles',
  REFRESH: 'auth/refresh',
  ROLES: 'roles',
  SIGN_UP: 'auth/register',
  USERNAME_CHECK: 'username-check',
  USERS: 'users',
} as const;
