export const ENDPOINTS = {
  APPROVE: 'approve',
  AUTHORS: 'authors',
  DRAFT: 'draft',
  GOOGLE: 'auth/google',
  GOOGLE_CALLBACK: 'auth/google/callback',
  HIERARCHY: 'hierarchy',
  HISTORY: 'history',
  IMAGES: 'images',
  LOGIN: 'auth/login',
  LOGOUT: 'auth/logout',
  ME: 'me',
  MODERATION: 'moderation',
  POSTS: 'posts',
  PROFILES: 'profiles',
  REFRESH: 'auth/refresh',
  REJECT: 'reject',
  REVISION: 'request-revision',
  ROLES: 'roles',
  SIGN_UP: 'auth/register',
  SUBMIT: 'submit',
  USERNAME_CHECK: 'username-check',
  USERS: 'users',
} as const;
