export const ENDPOINTS = {
  AUTH: 'auth',
  AUTHORS: 'authors',
  COMMENTS: 'comments',
  CONTRIBUTION_STATS: 'contribution-stats',
  GOOGLE: 'auth/google',
  GOOGLE_CALLBACK: 'auth/google/callback',
  HIERARCHY: 'hierarchy',
  IMAGES: 'images',
  ME: 'me',
  POST_VIEWS: 'post-views',
  POSTS: 'posts',
  PROFILES: 'profiles',
  ROLES: 'roles',
  USERNAME_CHECK: 'username-check',
  USERS: 'users',
} as const;
